/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    users: User
    media: Media
    properties: Property
  }
  globals: {}
}

export interface User {
  id: string
  updatedAt: string
  createdAt: string
  email: string
  resetPasswordToken?: string
  resetPasswordExpiration?: string
  salt?: string
  hash?: string
  loginAttempts?: number
  lockUntil?: string
  password?: string
}

export interface Media {
  id: string
  alt: string
  updatedAt: string
  createdAt: string
  url?: string
  filename?: string
  mimeType?: string
  filesize?: number
  width?: number
  height?: number
}

export interface Property {
  id: string
  title: string
  price: number
  location: string
  status: 'for-sale' | 'for-rent' 
  type?: 'house' | 'apartment' | 'condo' | 'land' 
  bedrooms?: number
  bathrooms?: number
  area?: number
  yearBuilt?: number
  description?: any
  images?: (string | Media)[]
  slug?: string
  updatedAt: string
  createdAt: string
}
